# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The base value is
# useful for version/bar-numbering revisions:
file_template = %%(year)d%%(month).2d%%(day).2d_%%(rev)s_%%(slug)s

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to zoneinfo.zoneinfo()
# leave blank for localtime:
timezone = Asia/Shanghai

# max length of characters to apply to the
# "slug" field
truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .hcolor/other text
# files in the alembic directory to be copied
# alongside migrations instead of in the files/
# uder migrations:
output_encoding = utf-8

# the url database description that will be used
# for autogenerate. The value is set to the
# DATABASE_URL from the environment:
sqlalchemy.url = mysql+pymysql://root:1234@127.0.0.1:3306/algoviz_db?charset=utf8mb4

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
